'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { usePathname } from 'next/navigation';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideNavbarRoutes = ['/login', '/register']; // add others as needed
  return (
    <html lang="en">
      <body className={inter.className}>
      {!hideNavbarRoutes.includes(pathname) && <Navbar />}
        {children}
        </body>
    </html>
  );
}
